Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,18 +1,20 @@
 #!/bin/bash
 
 echo ""
-echo "-----> Installing ACT Heroku Buildpack ..."
-echo ""
 
-BUILD_DIR=$1
+BUILD_DIR=${1:-}
+VENDOR_DIR="vendor"
 ACT_VERSION=v0.2.26
 ACT_FILE_NAME=act_Linux_arm64.tar.gz
 DOWNLOAD_LINK=https://github.com/nektos/act/releases/download/$ACT_VERSION/$ACT_FILE_NAME
 
-INSTALL_DIR=$BUILD_DIR/vendor/act/
-ACT_DIR=${HOME}/vendor/act
-
-mkdir -p $INSTALL_DIR
+echo "-----> Downloading ACT Binary ..."
+echo ""
+cd $BUILD_DIR
+mkdir -p $VENDOR_DIR
+cd $VENDOR_DIR
+mkdir -p act
+cd act
 code=$(curl "$DOWNLOAD_LINK" -L --silent --fail --retry 5 --retry-max-time 15 -o ./$ACT_FILE_NAME --write-out "%{http_code}")
 
 if [ "$code" != "200" ]; then
@@ -20,13 +22,20 @@ if [ "$code" != "200" ]; then
   echo "       Error: $code" && exit 1
 fi
 
+echo "-----> Unpacking ACT Binary ..."
+echo ""
 tar -xf "./$ACT_FILE_NAME" --strip-components=1
 
+if [ "$?" != "0" ]; then
+  echo "-----> Failed to unpack ..." && exit 1
+fi
+
 echo "-----> Building Runtime Environment for ACT ..."
+rm $ACT_FILE_NAME
 echo ""
 PROFILE_PATH="$BUILD_DIR/.profile.d/act.sh"
 mkdir -p $(dirname $PROFILE_PATH)
-echo 'export PATH="$PATH:${HOME}/.heroku/vendor"' >> $PROFILE_PATH
+echo 'export PATH="$PATH:${HOME}/vendor/act"' >> $PROFILE_PATH
 
 echo "-----> Successfully Installed ACT Buildpack !!"
 echo ""
